name: "Test"
on: 
  workflow_dispatch:
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission
        id: Permission
        run: chmod +x ./.github/initojson.sh       
      - name: Pass Project 
        id: pass-project
        run: echo "project=$(cat project.godot | ./.github/initojson.sh | jq 'tojson')" >> GITHUB_OUTPUT               
      - name: Pass Exports  
        id: pass-exports
        run: echo "export=$(cat export_presets.cfg | ./.github/initojson.sh | jq 'tojson')" >> GITHUB_OUTPUT
      - name: Pass Indexes  
        id: pass-idxs
        run: echo "export_idxs=$(cat export_presets.cfg | ./.github/initojson.sh | jq '.mat_idxs | tojson')" >> GITHUB_OUTPUT
    outputs: 
      project: ${{ steps.pass-project.outputs.project }}
      export: ${{ steps.pass-exports.outputs.export }}
      export_idxs: ${{ steps.pass-idxs.outputs.export_idxs }}
  test2:
    needs: test1
    name: Test 2
    runs-on: ubuntu-latest
#    env:
#      project: ${{ fromJSON(needs.test-1.outputs.project) }}
#      export: ${{ fromJSON(needs.test-1.outputs.export) }}
#    strategy:
#      matrix: 
#        idx: ${{ fromJSON(needs.test-1.outputs.export_idxs) }}
    steps:
      - run: |
          echo "${{toJSON(needs.test1.outputs)}}" 
#          echo "idx: ${{ needs.test1.outputs.export_idxs }}"
#          echo "export: ${{ needs.test1.outputs.export }}"
#          echo "project: ${{ needs.test1.outputs.project }}"
#          echo "--------------------"